Document: epics-mcore-utils
Title: Debian epics-mcore-utils Manual
Author: <insert document author here>
Abstract: This manual describes what epics-mcore-utils is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/epics-mcore-utils/epics-mcore-utils.sgml.gz

Format: postscript
Files: /usr/share/doc/epics-mcore-utils/epics-mcore-utils.ps.gz

Format: text
Files: /usr/share/doc/epics-mcore-utils/epics-mcore-utils.text.gz

Format: HTML
Index: /usr/share/doc/epics-mcore-utils/html/index.html
Files: /usr/share/doc/epics-mcore-utils/html/*.html
